function xx0 = genInitEllip(pp,fig)
%% Read Me
% xx0 = genInitEllip(pp,fig) finds generates the initial ellipse for
% finding the minimum area ellipse containing a set of points. The initial
% ellipse is generated by circumscbribing an ellipse around the axis
% alligned box containing all of the points in pp.
%
% INPUTS
%   pp:  Set of N points that minimum area ellipse will contain. 
%           [Nx2 matrix]
%   fig: Optional flag for drawing the resulting ellipse. Default is false.
%           [Boolean]
%
% OUTPUTS
%   xx0: The affine transform coefficients of the initial ellipse.
%
%% Parse Inputs
if nargin == 1;
    fig = false;
end

%% Determine Size of Box Containing Points
xmin = min(pp(:,1));
xmax = max(pp(:,1));
S_maj = (xmax-xmin)*sqrt(2)/2;
h = (xmax+xmin)/2;

ymin = min(pp(:,2));
ymax = max(pp(:,2));
S_min = (ymax-ymin)*sqrt(2)/2;
k = (ymax+ymin)/2;

theta = pi/2;
p0 = [h;k];

%% Convert Parameters to Affine Transform Coefficients
[A,bb] = cgp2axc(S_maj,S_min,theta,p0,fig);

%% Map Parameters
xx0(1) = A(1,1);
xx0(2) = A(2,2);
xx0(3) = A(1,2);
xx0(4) = bb(1);
xx0(5) = bb(2);

%% Draw Figure if Necessary
if fig
    hold on
    scatter(pp(:,1),pp(:,2));
    hold off
end
